const Marty = require('marty');

module.exports = Marty.createConstants([
  'UPDATE_STARTING',
  'LOCATION_RECEIVED',
  'LOCATIONS_RECEIVED',
  'REMOVE_STARTING',
  'LOCATION_FORGET_TRIGGERED',
  'LOC_FORGET_SCHEDULED',
  'LOC_FORGET_RESCHEDULED',
  'USER_REMOVED'
]);
