import Marty from 'marty';

export default Marty.createConstants([
  'UPDATE_STARTING',
  'LOCATION_RECEIVED',
  'LOCATIONS_RECEIVED',
  'REMOVE_STARTING',
  'LOCATION_FORGET_TRIGGERED',
  'LOC_FORGET_SCHEDULED',
  'LOC_FORGET_RESCHEDULED',
  'LOC_REFRESH_TRIGGERED',
  'USER_REMOVED'
]);
